@hostname = http://localhost
@port = 3333
@host = {{hostname}}:{{port}}
@ctype = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
###

GET {{host}}/mail
###

GET {{host}}/
###

GET {{host}}/user
###

POST  {{host}}/createUser
content-type: {{ctype}}
{
    "name": "Calieno",
    "username": "calieno@gmail.com",
    "passwd":"1234"
}